# Generated by Django 3.2.18 on 2023-03-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_number', models.IntegerField(auto_created=True, unique=True)),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('counter', models.IntegerField()),
                ('cashier', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('payment_mode', models.IntegerField(choices=[(1, 'Cash Payment'), (2, 'Card Payment'), (3, 'UPI Payment')])),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
        ),
    ]
