# Generated by Django 3.2.18 on 2023-03-26 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20230326_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='grand_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='gst',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='BN00001', max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.bill', to_field='bill_number')),
            ],
        ),
    ]
