# Generated by Django 3.2.18 on 2023-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20230326_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.IntegerField(default=1000, unique=True),
        ),
    ]
