# Generated by Django 3.2.18 on 2023-03-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_bill_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billitems',
            old_name='total',
            new_name='amount',
        ),
    ]
