# Generated by Django 3.2.18 on 2023-03-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_alter_bill_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillItems',
            new_name='BillItem',
        ),
    ]
